// Assemble final HTML pages from src/layout.html + src/pages/*.html
import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";

const R = process.cwd();
const layout = fs.readFileSync(path.join(R, "src/layout.html"), "utf8");

// asset version (content hash of css+js) for cache-busting
const hashSrc = fs.readFileSync(path.join(R, "assets/css/styles.css")) + fs.readFileSync(path.join(R, "assets/js/main.js"));
const V = crypto.createHash("sha1").update(hashSrc).digest("hex").slice(0, 8);

// Portfolio statistics snapshot — generated by tools/fetch_portfolio_map.py from
// GOLD.DP_PortfolioDB (metroAreas comes from the Census-derived tools/msa_cache.json).
// Fallbacks keep the build working if the snapshot is absent.
const STATS_FALLBACK = { currentProperties: 422, totalProperties: 574, states: 40,
  storageUnits: 168966, squareFeet: 24816465, unitsSinceInception: 241139,
  transactions: 356, metroAreas: 120 };
let STATS = STATS_FALLBACK, STATS_ASOF = "";
try {
  const pj = JSON.parse(fs.readFileSync(path.join(R, "assets/data/portfolio.json"), "utf8"));
  STATS = { ...STATS_FALLBACK, ...(pj.stats || {}) };
  STATS_ASOF = pj.generated || "";
} catch { /* no snapshot yet — use fallbacks */ }

const floorTo = (n, step) => Math.floor(n / step) * step;
const num = (n) => Number(n).toLocaleString("en-US");
const fmtAsOf = (iso) => {
  if (!iso) return "December 31, 2025";
  const [y, m, d] = iso.split("-").map(Number);
  return new Date(Date.UTC(y, m - 1, d)).toLocaleDateString("en-US",
    { year: "numeric", month: "long", day: "numeric", timeZone: "UTC" });
};

// Prose figures (rounded down so the "more than / in excess of" hedges stay true).
const STAT_TOKENS = {
  "{{STAT_TOTAL_ROUND}}": num(floorTo(STATS.totalProperties, 5)),
  "{{STAT_TXN_ROUND}}": num(floorTo(STATS.transactions, 5)),
  "{{STAT_UNITS_INCEPTION_ROUND}}": num(floorTo(STATS.unitsSinceInception, 10000)),
  "{{STAT_AS_OF}}": fmtAsOf(STATS_ASOF),
};

// Build the six portfolio stat tiles (exact live counts; K+/M+ floored so "+" is true).
function buildPortfolioStats() {
  const tile = (n, label, suffix) =>
    `          <div class="stat"><span class="stat__num" data-count="${n}"` +
    `${suffix ? ` data-suffix="${suffix}"` : ""}>${num(n)}${suffix || ""}</span>` +
    `<span class="stat__label">${label}</span></div>`;
  return [
    tile(STATS.currentProperties, "Current Properties"),
    tile(STATS.states, "States"),
    tile(Math.floor(STATS.storageUnits / 1000), "Units", "K+"),
    tile(Math.floor(STATS.squareFeet / 1e6), "Square Feet", "M+"),
    tile(STATS.metroAreas ?? 133, "Metropolitan Areas"),
    tile(STATS.totalProperties, "Total Properties"),
  ].join("\n");
}

// LCP hero image to preload per page (relative to site root via @/)
const HERO_PRELOAD = {
  "home.html": "assets/img/storage_hallways.jpeg",
  "about.html": "assets/img/23-web-or-mls-DJI_20250107154046_0427_D-1024x576.jpg",
  "expertise.html": "assets/img/banner_expertise.jpg",
  "team.html": "assets/img/39-web-or-mls-DSC_1675-1536x1023.jpg",
  "portfolio.html": "assets/img/23-web-or-mls-DJI_20250107154046_0427_D-1024x576.jpg",
  "contact.html": "assets/img/contact-bg.jpg",
  "terms.html": "assets/img/blue_bricks-lg.png",
};

const PAGES = [
  { file: "home.html",      out: "index.html",                              active: "",          canon: "/",
    title: "Merit Hill Capital - Real Estate Investment Firm in New York",
    desc: "Merit Hill Capital is a woman-owned real estate investment firm focused on acquiring, owning, and managing self-storage facilities across the U.S." },
  { file: "about.html",     out: "about/index.html",                        active: "about",     canon: "/about/",
    title: "About Merit Hill Capital — Institutional Self-Storage Investor",
    desc: "Founded in 2016 by Liz Raun Schlesinger, Merit Hill Capital is a leading institutional self-storage investor with a disciplined, value-add approach." },
  { file: "expertise.html", out: "expertise/index.html",                    active: "expertise", canon: "/expertise/",
    title: "Self-Storage Investment Expertise — Merit Hill Capital",
    desc: "Why self-storage and how Merit Hill drives value: a needs-based asset class in a fragmented industry, with a proprietary evaluation and value-add process." },
  { file: "team.html",      out: "team/index.html",                         active: "team",      canon: "/team/",
    title: "Our Team — Merit Hill Capital Self-Storage",
    desc: "Meet the Merit Hill Capital team: experienced self-storage professionals dedicated to integrity, perseverance, and the success of our partners.",
    scripts: '<script src="@/assets/js/team-data.js"></script>' },
  { file: "portfolio.html", out: "portfolio/index.html",                    active: "portfolio", canon: "/portfolio/",
    title: "Self-Storage Portfolio — Merit Hill Capital",
    desc: "National reach, local expertise: Merit Hill Capital operates a diverse portfolio of 400+ self-storage properties across 39 states in the United States." },
  { file: "contact.html",   out: "contact/index.html",                      active: "contact",   canon: "/contact/",
    title: "Contact Merit Hill Capital — Self-Storage Investment",
    desc: "Contact Merit Hill Capital with questions or to sell your self-storage facility. Reach our Brooklyn, NY and Dallas, TX teams or email IR@merithillcapital.com." },
  { file: "terms.html",     out: "terms-and-conditions-of-use/index.html",  active: "",          canon: "/terms-and-conditions-of-use/",
    title: "Terms and Conditions of Use - Merit Hill Capital",
    desc: "Terms and Conditions of Use for the Merit Hill Capital website." },
];

// Display order of team members (matches the original merithillcapital.com/team grid).
// Integer-like object keys can't preserve order, so order is driven explicitly here.
const TEAM_ORDER = ["37","372","46","61","49","361","59","1163","1762","2249","2250","1637","2035","1760","2246","1725","1506","1505","harrison-carter","patrick-cheek","1721","1507","2233","1131","2039","1129","294","363","1617","1503","1160","969","1729"];

// Build the team grid markup from the generated team data (keeps names/titles/photos in sync).
function buildTeamGrid() {
  const js = fs.readFileSync(path.join(R, "assets/js/team-data.js"), "utf8");
  const json = js.replace(/^[\s\S]*?=\s*/, "").replace(/;\s*$/, "");
  const data = JSON.parse(json);
  const ids = [...TEAM_ORDER.filter((id) => data[id]), ...Object.keys(data).filter((id) => !TEAM_ORDER.includes(id))];
  const card = (id, d) =>
    `        <button class="team-card reveal" data-member="${id}">
          <img class="team-card__photo" src="${d.thumb}" alt="${(d.name || "").replace(/"/g, "&quot;")}" loading="lazy" width="220" height="220">
          <span class="team-card__name">${d.name || ""}</span>
          <span class="team-card__title">${d.title || ""}</span>
        </button>`;
  // The founder (first member) is featured on her own centered row above the grid, matching the original.
  const [firstId, ...restIds] = ids;
  const featured = `        <div class="team-featured">\n${card(firstId, data[firstId])}\n        </div>`;
  const grid = `        <div class="team-grid">\n${restIds.map((id) => card(id, data[id])).join("\n")}\n        </div>`;
  return `${featured}\n${grid}`;
}

// Build the original-style horizontal "zigzag" milestone timeline (mhts).
function buildTimeline() {
  const ms = JSON.parse(fs.readFileSync(path.join(R, "src/data/milestones.json"), "utf8"));
  const card = (m) => `<div class="mhts-card"><h5 class="mhts-card-title">${m.year}</h5><p class="mhts-card-desc">${m.desc}</p></div>`;
  const top = ms.map((m, i) => `<div class="mhts-item">${i % 2 === 0 ? card(m) : ""}</div>`).join("");
  const bot = ms.map((m, i) => `<div class="mhts-item">${i % 2 === 1 ? card(m) : ""}</div>`).join("");
  const mid = ms.map(() => `<div class="mhts-item"><div class="mhts-dot"></div></div>`).join("");
  return `<div class="mhts-wrap" id="mhts-wrap" data-total="${ms.length}">
          <button class="mhts-arrow mhts-prev" id="mhts-prev" aria-label="Previous milestones" disabled><svg width="18" height="18" viewBox="0 0 24 24" fill="none"><path d="M16.4 1.45L18.4 3.475L9.825 12.05L18.4 20.625L16.4 22.65L5.8 12.05L16.4 1.45Z" fill="currentColor"/></svg></button>
          <div class="mhts-vp" id="mhts-vp"><div class="mhts-track" id="mhts-track">
            <div class="mhts-row mhts-row-top">${top}</div>
            <div class="mhts-row mhts-row-mid" id="mhts-mid"><div class="mhts-line"></div>${mid}</div>
            <div class="mhts-row mhts-row-bot">${bot}</div>
          </div></div>
          <button class="mhts-arrow mhts-next" id="mhts-next" aria-label="Next milestones"><svg width="18" height="18" viewBox="0 0 24 24" fill="none"><path d="M7.6 22.55L5.6 20.525L14.175 11.95L5.6 3.375L7.6 1.35L18.2 11.95L7.6 22.55Z" fill="currentColor"/></svg></button>
          <div class="mhts-progress" aria-hidden="true"><span class="mhts-progress__bar" id="mhts-bar"></span></div>
        </div>`;
}

let built = 0;
for (const pg of PAGES) {
  const depth = pg.out.split("/").length - 1;
  const prefix = depth === 0 ? "" : "../".repeat(depth);
  let main = fs.readFileSync(path.join(R, "src/pages", pg.file), "utf8");
  if (pg.file === "team.html") main = main.replace("{{TEAM_GRID}}", buildTeamGrid());
  if (pg.file === "about.html") main = main.replace("{{TIMELINE}}", buildTimeline());
  if (pg.file === "portfolio.html") main = main.replace("{{PORTFOLIO_STATS}}", buildPortfolioStats());

  let html = layout
    .replace("{{MAIN}}", main)
    .replace(/\{\{TITLE\}\}/g, pg.title)
    .replace(/\{\{DESC\}\}/g, pg.desc)
    .replace(/\{\{CANON\}\}/g, pg.canon)
    .replace(/\{\{V\}\}/g, V)
    .replace("{{HEROPRELOAD}}", HERO_PRELOAD[pg.file]
      ? `  <link rel="preload" as="image" href="@/${HERO_PRELOAD[pg.file]}" fetchpriority="high">\n` : "")
    .replace("{{BODYSCRIPTS}}", pg.scripts || "");

  // data-driven statistic tokens (prose figures + as-of date)
  for (const [tok, val] of Object.entries(STAT_TOKENS)) html = html.split(tok).join(val);

  // active nav state
  if (pg.active) html = html.replace(`data-nav="${pg.active}"`, `data-nav="${pg.active}" aria-current="page"`);

  // resolve root-relative token
  html = html.split("@/").join(prefix);

  fs.mkdirSync(path.dirname(path.join(R, pg.out)), { recursive: true });
  fs.writeFileSync(path.join(R, pg.out), html);
  built++;
  console.log("built", pg.out);
}
console.log(`\n${built} pages built.`);

// sitemap.xml (canonical production domain)
const ORIGIN = "https://richiemhc.github.io/mhcsite";
const LASTMOD = new Date().toISOString().slice(0, 10);
const urls = PAGES.map((p) =>
  `  <url><loc>${ORIGIN}${p.canon}</loc><lastmod>${LASTMOD}</lastmod><changefreq>monthly</changefreq><priority>${p.canon === "/" ? "1.0" : "0.7"}</priority></url>`
).join("\n");
fs.writeFileSync(path.join(R, "sitemap.xml"),
  `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls}\n</urlset>\n`);
console.log("sitemap.xml written");
